# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
    # specify the version you desire here
    - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install dependencies
          working_directory: ~/repo
          command: |
            npm i

      - run:
          name: Update dependencies
          working_directory: ~/repo
          command: |
            npm i @mhy/config@latest
            npm i @mhy/build@latest
            npm i @mhy/process@latest
            npm i @mhy/boot@latest
            git config credential.helper 'cache --timeout=120'
            git config user.email "wintercounter@gmail.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -am "Updating dependencies [ci skip]"
            git push -q https://${GITHUB_REPO_TOKEN}@github.com/wintercounter/mhy.git master

      - deploy:
          name: Trigger deployment
          working_directory: ~/repo
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            sh ./ci.sh